seed: 42
device: cuda:0
num_steps_per_env: 128
max_iterations: 3000
empirical_normalization: true
policy:
  class_name: ActorCritic
  init_noise_std: 0.6
  actor_hidden_dims:
  - 256
  - 128
  - 64
  critic_hidden_dims:
  - 256
  - 128
  - 64
  activation: tanh
algorithm:
  class_name: PPO
  value_loss_coef: 1.0
  use_clipped_value_loss: true
  clip_param: 0.2
  entropy_coef: 0.005
  num_learning_epochs: 8
  num_mini_batches: 8
  learning_rate: 0.00025
  schedule: adaptive
  gamma: 0.99
  lam: 0.95
  desired_kl: 0.01
  max_grad_norm: 1.5
save_interval: 25
experiment_name: ur5_rl_direct
run_name: ''
logger: tensorboard
neptune_project: isaaclab
wandb_project: isaaclab
resume: false
load_run: .*
load_checkpoint: model_.*.pt
